spring:
  application:
    name: auth-bot

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/auth_bot_db
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

bot:
    username: authentication_t_bot
    token: 7641740982:AAEkkEu_1BVOJYOVVMEvmYpgnPuUkm2LMvM